dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
  - deploy
  - migrate
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      addons:
        mariadb: '10.2'
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "target/student-registration-0.1.0.jar"
        skip_cleanup: true
    - stage: deploy
      language: java
      script:
        - echo "Downloading allocations server $RELEASE_TAG"
        - wget -P applications/allocations-server/build/libs https://github.com/$GITHUB_USERNAME/student-registration/releases/download/$RELEASE_TAG/student-registration-0.1.0.jar
      before_deploy:
        - cp manifest-allocations.yml manifest.yml
        - echo "Deploying allocations server $RELEASE_TAG"
      deploy: &cloudfoundry
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: kerim.strikovic@asynchrony.com
    - stage: migrate
      language: java
      before_install:
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
      script:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s review
        - ./gradlew cfMigrate
